version: "3.6"
services:
  web:
    image: justinclift/db4s-downloader:v0.10.armv8
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "3.0"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - "/etc/letsencrypt/archive/download.sqlitebrowser.org:/certs"
      - "/root/data:/data"
    networks:
      - bridge
networks:
  bridge:
    external: true
    name: bridge
