version: "3"
services:
  web:
    image: justinclift/db4s-downloader:v0.8.armv8
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "1.0"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "443:443"
    volumes:
      - "/etc/letsencrypt/archive/download.sqlitebrowser.org:/certs"
      - "/root/data:/data"
    networks:
      - webnet
#  visualizer:
#    image: dockersamples/visualizer:stable
#    ports:
#      - "8080:8080"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#    deploy:
#      placement:
#        constraints: [node.role == manager]
#    networks:
#      - webnet
networks:
  webnet:

