version: "3"
services:
  web:
    image: justinclift/db4s-downloader:v0.1.x64
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "1.0"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "443:443"
    volumes:
      - "/home/docker/data:/data"
    networks:
      - webnet
#  pg:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: example
#    volumes:
#      - "/var/lib/postgresql/data:/var/lib/postgresql/data"
networks:
  webnet:

